EXAMPLE='
    root=white,black
    border=black,lightgray
    window=lightgray,lightgray
    shadow=black,gray
    title=black,lightgray
    button=black,cyan
    actbutton=white,cyan
    compactbutton=black,lightgray
    checkbox=black,lightgray
    actcheckbox=lightgray,cyan
    entry=black,lightgray
    disentry=gray,lightgray
    label=black,lightgray
    listbox=black,lightgray
    actlistbox=black,cyan
    sellistbox=lightgray,black
    actsellistbox=lightgray,black
    textbox=black,lightgray
    acttextbox=black,cyan
    emptyscale=,gray
    fullscale=,cyan
    helpline=white,black
    roottext=lightgrey,black
'
MY_COLORS='
    root=white,black
    window=black,black
    border=white,black
    textbox=white,black
    label=blue,black
    listbox=white,black
    title=red,black
    actlistbox=white,black
    actcheckbox=black,black
    button=white,red
    compactbutton=white,black
    actlistbox=black,cyan
 
'

export NEWT_COLORS=$MY_COLORS
nmtui
